# Uncomment the next line to define a global platform for your project
platform :ios, '13.4'

target 'unsplahAPI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'SDWebImage', '~> 5.0'
  pod 'Swinject'
  pod 'NetworkAPI', '~> 1.0.0'
  
end
